# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ITlea\OneDrive\Bureau\Projet_PFA\AddCar\register-form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 500)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 380, 480))
        self.widget.setStyleSheet("background-color:rgba(16,16,16,255);\n"
"border-radius:20px;\n"
"")
        self.widget.setObjectName("widget")
        self.t3 = QtWidgets.QLineEdit(self.widget)
        self.t3.setGeometry(QtCore.QRect(10, 150, 361, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.t3.setFont(font)
        self.t3.setStyleSheet("background-color:rgba(47,49,52,200);\n"
"color:rgb(255,255,255);\n"
"border-radius:2px;\n"
"padding-left:10px;\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"padding-bottom:3px;")
        self.t3.setObjectName("t3")
        self.t4 = QtWidgets.QLineEdit(self.widget)
        self.t4.setGeometry(QtCore.QRect(10, 200, 361, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.t4.setFont(font)
        self.t4.setStyleSheet("background-color:rgba(47,49,52,200);\n"
"color:rgb(255,255,255);\n"
"border-radius:2px;\n"
"padding-left:10px;\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"padding-bottom:3px;")
        self.t4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.t4.setObjectName("t4")
        self.b3 = QtWidgets.QPushButton(self.widget)
        self.b3.setGeometry(QtCore.QRect(10, 360, 361, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.b3.setFont(font)
        self.b3.setStyleSheet("QPushButton#b3{\n"
"background-color:rgb(255,191,16);\n"
"color:rgb(0,0,0);\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#b3:pressed{\n"
"background-color:rgb(255,255,16);\n"
"\n"
"\n"
"}")
        self.b3.setObjectName("b3")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(150, 30, 91, 111))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255,191,16);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(120, 400, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255,191,16);")
        self.label_2.setObjectName("label_2")
        self.b4 = QtWidgets.QPushButton(self.widget)
        self.b4.setGeometry(QtCore.QRect(130, 430, 131, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.b4.setFont(font)
        self.b4.setStyleSheet("QPushButton#b4{\n"
"background-color:rgb(255,191,16);\n"
"color:rgb(0,0,0);\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#b4:pressed{\n"
"background-color:rgb(255,255,16);\n"
"\n"
"\n"
"}")
        self.b4.setObjectName("b4")
        self.t5 = QtWidgets.QLineEdit(self.widget)
        self.t5.setGeometry(QtCore.QRect(10, 250, 361, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.t5.setFont(font)
        self.t5.setStyleSheet("background-color:rgba(47,49,52,200);\n"
"color:rgb(255,255,255);\n"
"border-radius:2px;\n"
"padding-left:10px;\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"padding-bottom:3px;")
        self.t5.setObjectName("t5")
        self.t6 = QtWidgets.QLineEdit(self.widget)
        self.t6.setGeometry(QtCore.QRect(10, 300, 361, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.t6.setFont(font)
        self.t6.setStyleSheet("background-color:rgba(47,49,52,200);\n"
"color:rgb(255,255,255);\n"
"border-radius:2px;\n"
"padding-left:10px;\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"padding-bottom:3px;")
        self.t6.setObjectName("t6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.t3.setPlaceholderText(_translate("Form", "Enter your username"))
        self.t4.setPlaceholderText(_translate("Form", "Enter your password"))
        self.b3.setText(_translate("Form", "R e g i s t e r"))
        self.label.setText(_translate("Form", ""))
        self.label_2.setText(_translate("Form", "Already Registered Login"))
        self.b4.setText(_translate("Form", "L o g i n  N o w"))
        self.t5.setPlaceholderText(_translate("Form", "Enter your email"))
        self.t6.setPlaceholderText(_translate("Form", "Enter your phone"))
